### ISSUE TITLE
Setup Labeling Software

### ISSUE THREAD

**Issue by eddieliao** [ut-ras/robomaster_cv#3]
We need to research and setup a labeling software for our dataset. Please include setup instructions (ideally in the README.md) so that all members can contribute to labeling.

We will need the following labels:
- Red
- Blue
- Robot identifier (1, 2, 3, sentry, base)
- Full robot

**Comment by eddieliao** [comment]
https://terra-1-g.djicdn.com/b2a076471c6c4b72b574a977334d3e05/RM2023/RoboMaster%202023%20University%20Series%20Robot%20Building%20Specifications%20Manual%20V2.0%EF%BC%8820230713%EF%BC%89.pdf#%5B%7B%22num%22%3A700%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C54%2C784%2C0%5D

See here for labels for each robot

**Comment by Redfalcon5-ai** [comment]
10/06 - 

We started with the above dataset and setup a Roboflow project with the following object classes (2, 7, red, blue, robot):
![Screenshot 2023-10-09 181526](https://github.com/ut-ras/robomaster_cv/assets/71303491/5f204ca5-820d-4898-a471-322df9c9fe89)

We labeled the images by layering the annotations in the following way:
![Screenshot 2023-10-09 181956](https://github.com/ut-ras/robomaster_cv/assets/71303491/920fedda-9b12-47b7-9047-9eea2bee7ef1)
![Screenshot 2023-10-09 182015](https://github.com/ut-ras/robomaster_cv/assets/71303491/6fc85a0b-1ffb-426e-94b4-6667d26ccaef)

We labeled 30 images and trained a model on Roboflow, which yielded the following results:

Passing in an unlabeled image from the dataset (50% confidence threshold):
![Screenshot 2023-10-09 182429](https://github.com/ut-ras/robomaster_cv/assets/71303491/eab0108d-38c8-4114-9126-94b5998a589c)

Passing in a random image of robomasters from the internet (50% confidence threshold):
![Screenshot 2023-10-09 182453](https://github.com/ut-ras/robomaster_cv/assets/71303491/0cb86ace-b63c-4d41-a0a7-f85942de5106)

Same random image at 5% confidence:
![Screenshot 2023-10-09 182608](https://github.com/ut-ras/robomaster_cv/assets/71303491/2b070e40-7b22-438d-bc89-d358a5a4a6e5)

**Comment by eddieliao** [comment]
Were y'all able to obtain a Roboflow sponsorship by any chance? Or was this done using their free tier?

**Comment by Redfalcon5-ai** [comment]
The account we're using has a 14-day free trial of premium features. That being said, we didn't actually use any premium features for this. Roboflow has this form to apply for credits: https://docs.google.com/forms/d/e/1FAIpQLSfxpB8odH94M-7A4mI1LEaO3TQukVAVZ81KqMLW_stJD5ZG7Q/viewform
but we didn't know the answer to a lot of these (some of them are probably questions to be answered after using the free tier for a while). Also the free tier only allows us to use 10k images, which they increase to 100K if we apply for and get credits.

**Comment by eddieliao** [comment]
Setup is done, closing.
